Feature/add versioning
aws-samples/eks-anywhere-addons pull request #212
Opened 2024-02-12 19:00 UTC by mikemcd3912

*Issue #, if available:*
#125 

*Description of changes:*
Added label to the README for new labeling requirements
Updated partner Namespace files with the current versions based on available Helm chart versions
Updated Validated Partner files for each environment with the Version field and associated values

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-12 19:04 UTC, mikemcd3912 commented
GH Action failed because I updated the Validated Partners files outside of the expected workflow, and is expected behavior

2024-02-12 20:00 UTC, elamaran11 requested changes
@mikemcd3912  Nice work, couple of comments. We should use Automation to update the Partner list with Versions. We should not update manually. And Reason why manifestJob was removed.

2024-02-12 20:49 UTC, mikemcd3912 commented on Validated_Partners/baremetal_Partners.txt
> +VENDOR_PRODUCT   VENDOR_PRODUCT_TYPE            VENDOR_PRODUCT_VERSION
Reverted to prior state, To be updated by workflow after update

2024-02-12 20:49 UTC, mikemcd3912 commented on Validated_Partners/eks-local-clusters-outposts_Partners.txt
> +dynatrace        dynatrace                      0.10.1
Reverted to prior state, To be updated by workflow after update

2024-02-12 20:50 UTC, mikemcd3912 commented on Validated_Partners/vsphere_Partners.txt
> +accuknox         kubearmor                      v0.10.2
Reverted to prior state, To be updated by workflow after update

2024-02-12 20:50 UTC, mikemcd3912 commented on Validated_Partners/snow_Partners.txt
> +accuknox         kubearmor                      v0.10.2
Reverted to prior state, To be updated by workflow after update

2024-02-12 20:55 UTC, mikemcd3912 commented
I pulled ManifestJob because it seemed like it was associated with testing and therefore would serve as a distraction from our current examples for ChronJobs in the Testers folder. Updated PR to remove that deletion only modify Version update files

2024-02-12 20:59 UTC, elamaran11 commented
> I pulled ManifestJob because it seemed like it was associated with testing and therefore would serve as a distraction from our current examples for ChronJobs in the Testers folder. Updated PR to remove that deletion only modify Version update files

It is a sample. I think our `ReadMe` references this if im not mistaken. Lets keep it as a source of sample to share to partners who ask. This helps us being not biased to share any particular partner sample to anyone!

2024-02-16 19:10 UTC, elamaran11 approved these changes
LG

2024-02-16 19:10 UTC, merged

2024-04-20 00:00 UTC, elamaran11 commented
Looks like your deployment `dynatrace-dynatrace-operator` is failing.
Specifically, it looks like these pods are failing: 
* Pod: `dynatrace-dynatrace-operator-6859dbbd89-7n2sx`.
----