Address https://github.com/aws-samples/eks-anywhere-addons/pull/255#is…
aws-samples/eks-anywhere-addons pull request #261
Opened 2024-04-29 17:05 UTC by PetrMc

…suecomment-2083122552

*Issue #, if available:*

*Description of changes:*

Added "DiscoverySelectors"

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-04-29 17:58 UTC, elamaran11 commented
@PetrMc Thankyou for such a quick turnaround. We did a revert so your changes from last week is missing in the PR. Please sync your fork and then push the changes.

2024-04-29 18:15 UTC, PetrMc commented
sorry missed it. Should be good to go now.

2024-05-02 13:42 UTC, elamaran11 requested changes
@PetrMc Could you make this change?

2024-05-02 13:42 UTC, elamaran11 commented on eks-anywhere-common/Addons/Partner/Solo.io/solo-istiod.yaml
> +    meshConfig:
@PetrMc Would you be able to make this change for both service mesh to work together in same cluster.

2024-05-02 14:31 UTC, PetrMc commented
@elamaran11 @zirain - the requested change is applied, please let me know if anything else is needed.

2024-05-02 14:32 UTC, elamaran11 commented
> @elamaran11 @zirain - the requested change is applied, please let me know if anything else is needed.

Thankyou @PetrMc

2024-05-02 16:13 UTC, mikemcd3912 approved these changes
Thank you @PetrMc for the quick updates on this! Everything is working as expected and both PR's are co-existing on the cluster with that new edit applied. LGTM 

EKSA: 

- VMware (K8s 1.28, Bottlerocket 1.15): Pods deploy and reach a ready state, tester completes successfully on first attempt
- Outposts (K8s 1.27, Amazon Linux 2): Pods deploy and reach a ready state, tester completes successfully on first attempt
- Baremetal (K8s 1.27, Ubuntu 20.04.6 LTS): Pods deploy and reach a ready state, tester completes successfully on first attempt

EKS:

- EKS (K8s 1.28, ARM Bottlerocket 1.19): Pods deploy and reach a ready state, tester completes successfully on first attempt
- EKS (K8s 1.28, ARM Amazon Linux 2): Pods deploy and reach a ready state, tester completes successfully on first attempt
- EKS (K8s 1.28, x86 Amazon Linux 2): Pods deploy and reach a ready state, tester completes successfully on first attempt
- EKS (K8s 1.28, x86 Bottlerocket): Pods deploy and reach a ready state, tester completes successfully on first attempt

2024-05-02 16:18 UTC, elamaran11 approved these changes
LGTM

2024-05-02 16:19 UTC, merged

2024-05-05 03:00 UTC, elamaran11 commented
Looks like your deployment `istiod-1-18-3-solo` is failing.
Specifically, it looks like these pods are failing: 
* Pod: `istiod-1-18-3-solo-5f996795d8-czvmd`.
----

2024-05-06 16:12 UTC, PetrMc commented
@elamaran11 / @mikemcd3912 is there any action that are required on my end?